package e

const (
	//SUCCESS is Success code
	SUCCESS = 200
	//ERROR is err code
	ERROR = 500

	//INVALIDPARAMS is INVALID code
	INVALIDPARAMS = 400

	//ERROREXISTTAG is
	ERROREXISTTAG = 10001

	//ERRORNOTEXISTARTICLE is
	ERRORNOTEXISTARTICLE = 10003

	//ERRORAUTHCHECKTOKENFAIL is
	ERRORAUTHCHECKTOKENFAIL = 20001
	//ERRORAUTHCHECKTOKENTIMEOUT is
	ERRORAUTHCHECKTOKENTIMEOUT = 20002
	//ERRORAUTHTOKEN is
	ERRORAUTHTOKEN = 20003
	
	//ERRORAUTH is
	ERRORAUTH=20004
)
